/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bettingSol from "./Betting.sol";
export type { bettingSol };
export type { BettingApp } from "./BettingApp";
export * as factories from "./factories";
export type { BettingApp } from "./Betting.sol/BettingApp";
export { BettingApp__factory } from "./factories/Betting.sol/BettingApp__factory";
