/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BettingApp } from "./BettingApp";
export * as factories from "./factories";
export { BettingApp__factory } from "./factories/BettingApp__factory";
